name: Student API CI-TEST
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: studentdb
        ports:
          - 3307:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test
        run: mvn clean package
        env:
          SPRING_PROFILES_ACTIVATE: test
